### ISSUE TITLE
License

### ISSUE THREAD

**Issue by livibetter** [efferifick/wave#1]
Would that be possible for you to license _wave_ as open source?

I'd like to add a simple `Makefile` for installation and uninstallation, I plan to use it to play simple sounds as notification alert sounds for my system.

**Comment by efferifick** [comment]
Hope this works for you.

**Comment by efferifick** [comment]
I just want to add that this code was written a long time ago when I had less experience. I will be working this week on making it better (and safer). If it works for you on this state, great! Else, wait a bit. :)
