### ISSUE TITLE
--help and --version wait for input

### ISSUE THREAD

**Issue by livibetter** [efferifick/wave#2]
The `-h` and `-v` shouldn't be waiting for any inputs, it should print out the help or version and leaves, but instead:

```
% ./wave --version
wave version 0.02
[it waits here]
```

Same happening to `-h`, which  doesn't have a complete help message, by the way.

I'd attempt to fix this, but I am not sure @efferifick has done things he has planned to code for wave, so I am creating this issue. I don't want to contribute yet when things may change quite a bit.

**Comment by efferifick** [comment]
Thanks for pointing it out, I had finished rewriting the code but I forgot to exit after version and help were called. I am not thinking of drastically changing things anymore.
